title: Will Richardson
email: your-email@example.com
description: Will's photos
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://p.willhbr.net"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 21
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
