title: Will Richardson
author: Will Richardson
description: Will's photos
baseurl: ""
url: "https://pics.willhbr.net"

image_date: "%F.jpeg"
date_format: "%B %-d, %Y"
timezone: Australia/Sydney
link_date: "/%Y/%m/%d"

plugins:
  - jekyll-feed

exclude:
  - .jj
  - CNAME
  - Containerfile.local
  - Gemfile
  - Gemfile.lock
  - README.md
  - pods.yaml
  - publish.rb

sass:
  style: compressed

