title: Will Richardson
author: Will Richardson
description: Will's photos
baseurl: ""
url: "https://pics.willhbr.net"

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 21
paginate_path: "/page:num/"
